Traceback (most recent call last):
  File "/tmp/ipykernel_450911/4198299029.py", line 19, in model_pipeline
    training_results = training_model(model=model,
  File "/tmp/ipykernel_450911/3569148168.py", line 18, in training_model
    y_pred = model(images)
  File "/home/akshar/miniconda3/envs/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/akshar/miniconda3/envs/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1574, in _call_impl
    hook_result = hook(self, args, result)
  File "/home/akshar/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/wandb_torch.py", line 110, in <lambda>
    lambda mod, inp, outp: parameter_log_hook(
  File "/home/akshar/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/wandb_torch.py", line 97, in parameter_log_hook
    if not log_track_update(log_track):
  File "/home/akshar/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/wandb_torch.py", line 62, in log_track_update
    if log_track[LOG_TRACK_COUNT] < log_track[LOG_TRACK_THRESHOLD]:
TypeError: '<' not supported between instances of 'int' and 'str'