2024-02-15 19:22:19,649 INFO    MainThread:387333 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-15 19:22:19,649 INFO    MainThread:387333 [wandb_setup.py:_flush():76] Configure stats pid to 387333
2024-02-15 19:22:19,649 INFO    MainThread:387333 [wandb_setup.py:_flush():76] Loading settings from /home/akshar/.config/wandb/settings
2024-02-15 19:22:19,649 INFO    MainThread:387333 [wandb_setup.py:_flush():76] Loading settings from /home/akshar/Projects/Fraud_Classification/research/wandb/settings
2024-02-15 19:22:19,649 INFO    MainThread:387333 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-15 19:22:19,649 INFO    MainThread:387333 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-15 19:22:19,649 INFO    MainThread:387333 [wandb_init.py:_log_setup():526] Logging user logs to /home/akshar/Projects/Fraud_Classification/research/wandb/run-20240215_192219-79jlgq6q/logs/debug.log
2024-02-15 19:22:19,649 INFO    MainThread:387333 [wandb_init.py:_log_setup():527] Logging internal logs to /home/akshar/Projects/Fraud_Classification/research/wandb/run-20240215_192219-79jlgq6q/logs/debug-internal.log
2024-02-15 19:22:19,649 INFO    MainThread:387333 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f2118d831c0>
2024-02-15 19:22:19,649 INFO    MainThread:387333 [wandb_init.py:init():566] calling init triggers
2024-02-15 19:22:19,649 INFO    MainThread:387333 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'epochs': 10, 'classes': 2, 'batch_size': 16, 'lr': 0.001, 'architecture': 'EfficientNet_B0', 'num_workers': 16}
2024-02-15 19:22:19,649 INFO    MainThread:387333 [wandb_init.py:init():616] starting backend
2024-02-15 19:22:19,650 INFO    MainThread:387333 [wandb_init.py:init():620] setting up manager
2024-02-15 19:22:19,653 INFO    MainThread:387333 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-15 19:22:19,654 INFO    MainThread:387333 [wandb_init.py:init():628] backend started and connected
2024-02-15 19:22:19,666 INFO    MainThread:387333 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-15 19:22:19,666 INFO    MainThread:387333 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-15 19:22:19,666 INFO    MainThread:387333 [wandb_init.py:init():720] updated telemetry
2024-02-15 19:22:19,669 INFO    MainThread:387333 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-15 19:22:25,566 ERROR   MainThread:387333 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-02-15 19:22:25,841 ERROR   MainThread:387333 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/home/akshar/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home/akshar/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-02-15 19:23:55,568 INFO    MainThread:387333 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-15 19:23:55,568 INFO    MainThread:387333 [wandb_setup.py:_flush():76] Configure stats pid to 387333
2024-02-15 19:23:55,568 INFO    MainThread:387333 [wandb_setup.py:_flush():76] Loading settings from /home/akshar/.config/wandb/settings
2024-02-15 19:23:55,568 INFO    MainThread:387333 [wandb_setup.py:_flush():76] Loading settings from /home/akshar/Projects/Fraud_Classification/research/wandb/settings
2024-02-15 19:23:55,568 INFO    MainThread:387333 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-15 19:23:55,568 INFO    MainThread:387333 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-15 19:23:55,569 INFO    MainThread:387333 [wandb_init.py:_log_setup():526] Logging user logs to /home/akshar/Projects/Fraud_Classification/research/wandb/run-20240215_192355-xasrjdfc/logs/debug.log
2024-02-15 19:23:55,569 INFO    MainThread:387333 [wandb_init.py:_log_setup():527] Logging internal logs to /home/akshar/Projects/Fraud_Classification/research/wandb/run-20240215_192355-xasrjdfc/logs/debug-internal.log
2024-02-15 19:23:55,569 INFO    MainThread:387333 [wandb_init.py:init():566] calling init triggers
2024-02-15 19:23:55,569 INFO    MainThread:387333 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'epochs': 10, 'classes': 2, 'batch_size': 16, 'lr': 0.001, 'architecture': 'EfficientNet_B0', 'num_workers': 16}
2024-02-15 19:23:55,569 INFO    MainThread:387333 [wandb_init.py:init():616] starting backend
2024-02-15 19:23:55,569 INFO    MainThread:387333 [wandb_init.py:init():620] setting up manager
2024-02-15 19:23:55,572 INFO    MainThread:387333 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-15 19:23:55,572 INFO    MainThread:387333 [wandb_init.py:init():628] backend started and connected
2024-02-15 19:23:55,581 INFO    MainThread:387333 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-15 19:23:55,581 INFO    MainThread:387333 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-15 19:23:55,581 INFO    MainThread:387333 [wandb_init.py:init():720] updated telemetry
2024-02-15 19:23:55,581 INFO    MainThread:387333 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-15 19:25:25,636 ERROR   MainThread:387333 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-02-15 19:25:25,775 ERROR   MainThread:387333 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/home/akshar/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home/akshar/miniconda3/envs/pytorch/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
